image: nvidia/cuda
build:
  stage: build
  script: make
  artifacts: 
    paths:
    - hello
    expire_in: 1 week

test1:
  stage: test
  script: ./hello


test2:
  stage: test
  script: ./hello
test3:
  stage: test
  script: ./hello
test4:
  stage: test
  script: ./hello
